services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    container_name: quarkus-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: ["./mvnw", "quarkus:dev"]

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    container_name: angular-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "start"]
